-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2026-09-24 12:26:40.024
-- Source database is: LostAndFound
-- Connection URL is: jdbc:derby://localhost:1527/LostAndFound;user=administrator;password=admin
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for schemas
-- ----------------------------------------------

CREATE SCHEMA "ADMINISTRATOR";

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "ADMINISTRATOR"."STUDENTUSER" ("USER_ID" INTEGER NOT NULL, "STUDENT_NUMBER" INTEGER);

CREATE TABLE "ADMINISTRATOR"."REPORT" ("REPORT_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "USER_ID" INTEGER, "ITEM_ID" INTEGER, "LOCATION_ID" INTEGER, "REPORT_TYPE" VARCHAR(15), "DATE_REPORTED" DATE, "DATE_OCCURRED" DATE, "STATUS" VARCHAR(10));

CREATE TABLE "ADMINISTRATOR"."STAFFUSER" ("USER_ID" INTEGER NOT NULL, "DEPARTMENT" INTEGER);

CREATE TABLE "ADMINISTRATOR"."ADMINUSER" ("USER_ID" INTEGER NOT NULL, "PERMISSION_LEVEL" INTEGER);

CREATE TABLE "ADMINISTRATOR"."ITEM" ("ITEM_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "USER_ID" INTEGER, "CATEGORY_ID" INTEGER, "LOCATION_ID" VARCHAR(100), "ITEM_NAME" VARCHAR(100), "DESCRIPTION" VARCHAR(20), "COLOR" VARCHAR(100), "BRAND" VARCHAR(100), "UNIQUE_MARKS" VARCHAR(100));

CREATE TABLE "ADMINISTRATOR"."CLAIM" ("CLAIM_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "REPORT_ID" INTEGER, "CLAIMANT_ID" INTEGER, "CLAIM_DATE" DATE, "STATUS" VARCHAR(10), "ADMIN_NOTES" VARCHAR(100));

CREATE TABLE "ADMINISTRATOR"."APPUSER" ("USER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(100), "EMAIL" VARCHAR(50), "PHONE" INTEGER, "ROLE" VARCHAR(20), "PASSWORD" VARCHAR(255) NOT NULL DEFAULT 'ChangeMe123456!');

CREATE TABLE "ADMINISTRATOR"."CATEGORY" ("CATEGORY_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CATEGORY_NAME" VARCHAR(30), "DESCRIPTION" VARCHAR(100));

CREATE TABLE "ADMINISTRATOR"."LOCATION" ("LOCATION_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CAMPUS_OR_AREA" VARCHAR(10), "BUILDING" VARCHAR(30), "DESCRIPTION" VARCHAR(100), "GPS_COORDINATES" DECIMAL(8,6));

CREATE TABLE "ADMINISTRATOR"."MESSAGES" ("MESSAGEID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "SENDER" VARCHAR(50) NOT NULL, "RECEIVER" VARCHAR(50) NOT NULL, "MESSAGE" VARCHAR(1000) NOT NULL, "SENTTIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "ADMINISTRATOR"."REPORT" ADD CONSTRAINT "SQL260807201233230" PRIMARY KEY ("REPORT_ID");

ALTER TABLE "ADMINISTRATOR"."ADMINUSER" ADD CONSTRAINT "SQL260807201232980" PRIMARY KEY ("USER_ID");

ALTER TABLE "ADMINISTRATOR"."STUDENTUSER" ADD CONSTRAINT "SQL260807201233020" PRIMARY KEY ("USER_ID");

ALTER TABLE "ADMINISTRATOR"."CLAIM" ADD CONSTRAINT "SQL260807201233380" PRIMARY KEY ("CLAIM_ID");

ALTER TABLE "ADMINISTRATOR"."APPUSER" ADD CONSTRAINT "SQL260807201232900" PRIMARY KEY ("USER_ID");

ALTER TABLE "ADMINISTRATOR"."CATEGORY" ADD CONSTRAINT "SQL260807201233120" PRIMARY KEY ("CATEGORY_ID");

ALTER TABLE "ADMINISTRATOR"."MESSAGES" ADD CONSTRAINT "SQL260914120104470" PRIMARY KEY ("MESSAGEID");

ALTER TABLE "ADMINISTRATOR"."LOCATION" ADD CONSTRAINT "SQL260807201233160" PRIMARY KEY ("LOCATION_ID");

ALTER TABLE "ADMINISTRATOR"."STAFFUSER" ADD CONSTRAINT "SQL260807201233070" PRIMARY KEY ("USER_ID");

ALTER TABLE "ADMINISTRATOR"."ITEM" ADD CONSTRAINT "SQL260807201233190" PRIMARY KEY ("ITEM_ID");

-- FOREIGN
ALTER TABLE "ADMINISTRATOR"."REPORT" ADD CONSTRAINT "SQL260807201233231" FOREIGN KEY ("USER_ID") REFERENCES "ADMINISTRATOR"."APPUSER" ("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."REPORT" ADD CONSTRAINT "SQL260807201233232" FOREIGN KEY ("ITEM_ID") REFERENCES "ADMINISTRATOR"."ITEM" ("ITEM_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."REPORT" ADD CONSTRAINT "SQL260807201233240" FOREIGN KEY ("LOCATION_ID") REFERENCES "ADMINISTRATOR"."LOCATION" ("LOCATION_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."ADMINUSER" ADD CONSTRAINT "SQL260807201232981" FOREIGN KEY ("USER_ID") REFERENCES "ADMINISTRATOR"."APPUSER" ("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."STUDENTUSER" ADD CONSTRAINT "SQL260807201233021" FOREIGN KEY ("USER_ID") REFERENCES "ADMINISTRATOR"."APPUSER" ("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."CLAIM" ADD CONSTRAINT "SQL260807201233381" FOREIGN KEY ("REPORT_ID") REFERENCES "ADMINISTRATOR"."REPORT" ("REPORT_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."CLAIM" ADD CONSTRAINT "SQL260807201233382" FOREIGN KEY ("CLAIMANT_ID") REFERENCES "ADMINISTRATOR"."APPUSER" ("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."STAFFUSER" ADD CONSTRAINT "SQL260807201233071" FOREIGN KEY ("USER_ID") REFERENCES "ADMINISTRATOR"."APPUSER" ("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."ITEM" ADD CONSTRAINT "SQL260807201233191" FOREIGN KEY ("USER_ID") REFERENCES "ADMINISTRATOR"."APPUSER" ("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ADMINISTRATOR"."ITEM" ADD CONSTRAINT "SQL260807201233192" FOREIGN KEY ("CATEGORY_ID") REFERENCES "ADMINISTRATOR"."CATEGORY" ("CATEGORY_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

